services:
  api:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - SPRING_SERVER_PORT=${SPRING_SERVER_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - MINIO_HOST=${MINIO_HOST}
      - MINIO_PUBLIC_BUCKET=${MINIO_PUBLIC_BUCKET}
    ports:
      - "${SPRING_SERVER_PORT}:${SPRING_SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    profiles:
      - all

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    profiles:
      - all
      - dev

  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z
    command: server --console-address ":${MINIO_WEBUI_PORT}" /data
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_USERNAME}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "${MINIO_WEBUI_PORT}:${MINIO_WEBUI_PORT}"
    volumes:
      - minio-data:/data
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - all
      - dev

  minio-buckets:
    image: minio/mc:RELEASE.2024-04-18T16-45-29Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio ${MINIO_HOST} ${MINIO_USERNAME} ${MINIO_PASSWORD};
      /usr/bin/mc mb minio/public;
      /usr/bin/mc anonymous set download minio/public;
      /usr/bin/mc mb minio/analyses;
      /usr/bin/mc anonymous set download minio/analyses;
      exit 0;
      "
    profiles:
      - all
      - dev

volumes:
  minio-data:
  postgres-data:
