spring:
  config:
    activate:
      on-profile: test

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  jackson:
    mapper:
      default-view-inclusion: true

minio:
  username: miniouser
  password: miniopassword
  host: http://127.0.0.1:9000
  public_bucket: public
  analyses_bucket: analyses
  put_object_part_size: 10485760
