spring:
  application:
    name: history

  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/pets_history
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  jackson:
    mapper:
      default-view-inclusion: true

server:
  address: 0.0.0.0
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    encoding:
      charset: utf-8
      force-response: true

springdoc:
  api-docs:
    version: OPENAPI_3_1
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    use-root-path: true

minio:
  username: miniouser
  password: miniopassword
  host: http://127.0.0.1:9000
  public_bucket: public
  analysis_bucket: analysis
  put_object_part_size: 10485760
