CREATE TABLE IF NOT EXISTS family_group
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_family_group PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS owner
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(128)                            NOT NULL,
    email        VARCHAR(256)                            NOT NULL,
    password     VARCHAR(256)                            NOT NULL,
    CONSTRAINT pk_owner PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS family_group_members
(
    family_group_id BIGINT,
    members_id BIGINT,
    CONSTRAINT fk_family_group_id FOREIGN KEY (family_group_id) REFERENCES family_group (id),
    CONSTRAINT fk_members_id FOREIGN KEY (members_id) REFERENCES owner (id)
);

ALTER TABLE IF EXISTS pet
    ADD COLUMN family_group_id BIGINT,
    ADD CONSTRAINT fk_family_group_id FOREIGN KEY (family_group_id) REFERENCES family_group (id)
