CREATE TABLE analysis_image
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url         VARCHAR(256)                            NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    analysis_id BIGINT,
    CONSTRAINT fk_analisys_id FOREIGN KEY (analysis_id) REFERENCES analysis (id),
    CONSTRAINT pk_analysis_image PRIMARY KEY (id)
);
